// Generated by https://quicktype.io

export interface ClasseWidget {
    widget: Widget;
}

export interface Widget {
    debug: string;
    window: Window;
    image: Image;
    text: Text;
}

export interface Image {
    src: string;
    name: string;
    hOffset: number;
    vOffset: number;
    alignment: string;
}

export interface Text {
    data: string;
    size: number;
    style: string;
    name: string;
    hOffset: number;
    vOffset: number;
    alignment: string;
    onMouseUp: string;
}

export interface Window {
    title: string;
    name: string;
    width: number;
    height: number;
}